baseURL: https://kashyab.com/
title: Kashyab J. Ambarani
paginate: 5
theme: charlolamode


menu:
    main:
        - name: About Me
          url: aboutme/
          weight: 30
        - name: Articles
          url: articles/
          weight: 20
        - name: Projects
          url: projects
          weight: 15


params:
    author: Kashyab J. Ambarani
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Hi there, I'm Kashyab!
        description: |
          22 year old software engineer curious about technology.

          I explore an array of problems and share my thoughts here.
        imageUrl: "/images/kashyab-web-pic.png"
        imageTitle: my image
        imageWidth: 250
        imageHeight: 250
    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/kashyab12"
        - name: linkedin
          url: "https://www.linkedin.com/in/kashyab-ambarani/"
        - name: email
          url: "mailto:iamkashyab@gmail.com?subject=Subject\ Here!"

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"


enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true


minify:
    disableXML: true