baseURL: https://kashyab.com/
title: Kashyab Ambarani
paginate: 5
theme: charlolamode
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

menu:
    main:
        - name: About Me
          url: aboutme/
          weight: 30
        # - name: Projects
        #   url: projects
        #   weight: 15


params:
    env: production
    # author: Kashyab J. Ambarani
    defaultTheme: auto
    disableSpecial1stPost: true
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: false
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: false
    mainSections:
      - projects
    profileMode:
        enabled: false
    # homeInfoParams:
    #     enabled: true

    socialIcons:
        - name: github
          url: "https://github.com/kashyab12"
        - name: twitter
          url: "https://twitter.com/kashyabja"
        - name: linkedin
          url: "https://www.linkedin.com/in/kashyab-ambarani/"
        - name: email
          url: "mailto:iamkashyab@gmail.com?subject=Subject\ Here!"

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"

    analytics:
      google:
        SiteVerificationTag: "G-WZ8S1TE8QB"


minify:
    disableXML: true